def tick_total(x , y , z):
    an = x * 15
    bn = y * 12
    cn = z * 9
    total = (an + bn + cn)
    return total
def main():
    a = int(input("enter the numbers of seats sold in class a"))
    b = int(input("enter the numbers of seats sold in class b"))
    c = int(input("enter the numbers of seats sold in class c"))
    ttl = tick_total(a , b , c)
    print("the total revenue generated by tickets is", ttl)
main()
